name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!
        id: hello-world # Add an ID to reference this step

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
        id: build-script # Add an ID to reference this step

      # Create a status check for the hello-world step
      - name: Create status check for hello-world
        run: echo "Success"
        if: success()
        id: hello-world-status
        status: success

      # Create a status check for the build-script step
      - name: Create status check for build-script
        run: echo "Success"
        if: success()
        id: build-script-status
        status: success
