name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Report status
        if: ${{ always() }}
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"state": "success", "description": "All tests passed", "context": "CI"}' \
          https://api.github.com/repos/Level-UP-Sakthi/testing-levelup/statuses/${{ github.sha }}
