name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: echo "Building..."

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: echo "Testing..."

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]  # Ensure that 'build' and 'test' jobs are completed before deployment

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: echo "Deploying..."

